@startuml
autonumber "<b>(##)"
!include style.puml
skinparam ArrowFontStyle plain
'https://plantuml.com/sequence-diagram

box Logic LOGIC_COLOR_T1
participant ":removeStudentCommand" as RemoveStudentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "s:Student" as Student MODEL_COLOR
end box

[-> RemoveStudentCommand : execute()
activate RemoveStudentCommand

RemoveStudentCommand --> Model : Get student's class
activate Model

autonumber stop
Model --> RemoveStudentCommand : sClass
deactivate Model

autonumber resume
RemoveStudentCommand --> Model : Get list of students
activate Model

autonumber stop
Model --> RemoveStudentCommand : sClassStudentList
deactivate Model

autonumber resume
RemoveStudentCommand --> Model : Get student
activate Model

autonumber stop
Model --> Student : retrieves student
activate Student

Student --> Model
deactivate Student

Model --> RemoveStudentCommand : s
deactivate Model

autonumber resume
RemoveStudentCommand --> Model : Get student's name
activate Model

autonumber stop
Model --> RemoveStudentCommand : sName
deactivate Model

autonumber resume
RemoveStudentCommand --> Model : Delete student from class list
activate Model

autonumber stop
Model --> RemoveStudentCommand
deactivate Model

autonumber resume
RemoveStudentCommand --> Model : Delete student from EduTrack list
activate Model

autonumber stop
Model --> RemoveStudentCommand
deactivate Model

Student -[hidden]-> RemoveStudentCommand
Student -[hidden]-> RemoveStudentCommand
destroy Student

[<-- RemoveStudentCommand
deactivate RemoveStudentCommand

@enduml
