@startuml
!include style.puml
skinparam ArrowFontStyle plain
'https://plantuml.com/sequence-diagram

box Logic LOGIC_COLOR_T1
participant ":removeStudentCommand" as RemoveStudentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "s:Student" as Student MODEL_COLOR
end box

[-> RemoveStudentCommand : execute()
activate RemoveStudentCommand

RemoveStudentCommand --> Model : getClass(studentClassName)
activate Model

Model --> RemoveStudentCommand : sClass
deactivate Model

RemoveStudentCommand --> Model : getStudentList()
activate Model


Model --> RemoveStudentCommand : sClassStudentList
deactivate Model

RemoveStudentCommand --> Model : get(studentIndex)
activate Model

Model --> Student : retrieves student
activate Student

Student --> Model
deactivate Student

Model --> RemoveStudentCommand : s
deactivate Model

RemoveStudentCommand --> Model : deleteStudentFromClass(s, sClass)
activate Model


Model --> RemoveStudentCommand
deactivate Model

RemoveStudentCommand --> Model : deleteStudent(s)
activate Model

Model --> RemoveStudentCommand
deactivate Model

RemoveStudentCommand --> Student : getName()
activate Student

Student --> RemoveStudentCommand : sName
deactivate Student

Student -[hidden]-> RemoveStudentCommand
destroy Student

[<-- RemoveStudentCommand
deactivate RemoveStudentCommand

@enduml
